# Dockerfile for Spark applications
FROM bitnami/spark:3.4.1-debian-11-r40

USER root

# Install Python packages needed for Spark jobs
RUN pip install alpha_vantage pandas pyarrow redis psycopg2-binary

# Copy Spark scripts
COPY spark_streaming.py /app/
COPY spark_batch.py /app/

USER 1001
